// backend/data.js
const data = {
  products: [
    {
      sku: '000001',
      name: 'Signature Bianco Matte Ceramic Subway Wall Tile - 3 x 6 in.',
      slug: 'signature-bianco-matte-ceramic-subway-wall-tile',
      badge: 'new',
      tileCollection: ['Ceramic Wall Tile', 'Signature Tile Collection'], // ✅ renamed
      material: 'Ceramic Tile',
      application: ['Backsplash Tile', 'Wall Tile'],
      imageGallery: ['/images/p1.jpeg'],
      pricing: {
        perBox: 73.17,
        perSqFt: 7.09,
        sample: 3.0,
      },
      coverageSqFtPerBox: 10.32,
      finishOptions: ['Gloss', 'Matte'],
      colorOptions: [
        'Bianco',
        'Black',
        'Denim',
        'Fog Grey',
        'Gris',
        'Gunmetal',
        'Ivory',
        'Mint',
        'Oatmeal',
        'Pewter',
        'Slat Blue',
      ],
      sizeShape: ['4 x 8 in. Rectangle', '4 x 16 in. Rectangle'],
      availableInThisCollection: ['Tile', 'Trim & Accesories'],
      countInStock: 10,
      brandInfo: 'Bianco',
      rating: 4.5,
      numReviews: 10,
      description: 'Matte subway wall tile',
    },
    {
      sku: '000002',
      name: 'Mallorca White Ceramic Wall Tile - 2.5 x 8 in.',
      slug: 'mallorca-white-ceramic-wall-tile',
      badge: 'limited',
      tileCollection: ['Ceramic Wall Tile'], // ✅ renamed
      material: 'Ceramic Tile',
      application: ['Backsplash Tile', 'Wall Tile'],
      imageGallery: ['/images/p2.jpeg'],
      pricing: {
        perBox: 63.44,
        perSqFt: 11.79,
        sample: 3.0,
      },
      coverageSqFtPerBox: 5.38,
      finishOptions: [''],
      colorOptions: [''],
      sizeShape: [''],
      availableInThisCollection: ['Tile', 'Trim & Accesories'],
      countInStock: 10,
      brandInfo: 'Mallorca',
      rating: 4.0,
      numReviews: 8,
      description: 'Pearlescent subway wall tile',
    },
    {
      sku: '000003',
      name: 'Riad White Ceramic Wall Tile - 4 x 4 in.',
      slug: 'riad-white-ceramic-wall-tile',
      badge: 'new',
      tileCollection: ['Ceramic Wall Tile'], // ✅ renamed
      material: 'Ceramic Tile',
      application: ['Backsplash Tile', 'Wall Tile'],
      imageGallery: ['/images/p3.jpeg'],
      pricing: {
        perBox: 68.3,
        perSqFt: 12.69,
        sample: 3.0,
      },
      coverageSqFtPerBox: 5.38,
      finishOptions: [''],
      colorOptions: ['Sand', 'White'],
      sizeShape: [''],
      availableInThisCollection: [''],
      countInStock: 10,
      brandInfo: 'Riad',
      rating: 4.5,
      numReviews: 10,
      description: 'Moroccan-inspired white ceramic wall tile',
    },
    {
      sku: '000004',
      name: 'Kasbah Star Bone Porcelain Wall and Floor Tile - 6.5 x 6.5 in.',
      slug: 'kasbah-star-bone-porcelain-wall-and-floor-tile',
      badge: 'limited',
      tileCollection: ['Porcelain Wall Tile', 'Porcelain Floor Tile'], // ✅ renamed
      material: 'Porcelain Tile',
      application: ['Backsplash Tile', 'Floor Tile', 'Wall Tile'],
      imageGallery: ['/images/p4.jpeg'],
      pricing: {
        perBox: 70.0,
        perSqFt: 13.19,
        sample: 3.0,
      },
      coverageSqFtPerBox: 5.31,
      finishOptions: [''],
      colorOptions: ['Bone', 'Terracotta'],
      sizeShape: ['4.7 x 4.7 in. Cross', '6.5 x 6.5 in. Star'],
      availableInThisCollection: [''],
      countInStock: 10,
      brandInfo: 'Kasbah',
      rating: 4.5,
      numReviews: 10,
      description: 'Moroccan Zellige porcelain wall and floor tile',
    },
    {
      sku: '000005',
      name: 'Lincoln White Polished Porcelain Wall and Floor Tile - 12 x 24 in.',
      slug: 'lincoln-white-polished-porcelain-wall-and-floor-tile',
      badge: 'new',
      tileCollection: ['Ceramic Wall Tile', 'Ceramic Floor Tile'], // ✅ renamed
      material: 'Ceramic Tile',
      application: ['Backsplash Tile', 'Floor Tile', 'Wall Tile'],
      imageGallery: ['/images/p5.jpeg'],
      pricing: {
        perBox: 116.13,
        perSqFt: 9.99,
        sample: 3.0,
      },
      coverageSqFtPerBox: 11.63,
      finishOptions: [''],
      colorOptions: [''],
      sizeShape: ['12 x 24 in. Rectangle', '24 x 48 in. Rectangle'],
      availableInThisCollection: [''],
      countInStock: 15,
      brandInfo: 'Lincoln',
      rating: 4.5,
      numReviews: 10,
      description:
        'Inspired by the marble used for the Lincoln Memorial in Washington, D.C.',
    },
  ],
};

export default data;
